name: auth_manager
description: Auth Manager is used by Unwired library to manage to authentication. Extend AuthManager class to create your own implementation.
version: 1.1.0
homepage: https://github.com/Ayush-Suman/auth_manager

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
